### PR TITLE
Added ffmpeg

### PR DESCRIPTION
**Pull request by Jiyvn**
Install ffmpeg to support recording longer than 180 sec
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java#L102

### CODE REVIEW

**Comment by budtmo** [comment]
Hi @Jiyvn , 

Thank you for the PR. could you approve the EasyCLA? so I can merge the PR

**Comment by Jiyvn** [comment]
@budtmo done.

**Review by budtmo — APPROVED** [review]

**Comment by jlipps** [comment]
Hi @Jiyvn , congrats, the Appium project wants to compensate you for this (and perhaps other) contribution(s) this month! Please reply to this comment mentioning me and sharing your [OpenCollective](https://opencollective.com) account name, so that we can initiate payment! Or let me know if you decline to receive compensation via OpenCollective. Thank you!

**Comment by Jiyvn** [comment]
Hi @jlipps sorry for the late reply. I'm new to OpenCollective, glad to hear that the contributors of open source projects are being sponsored and compensated. I didn't expect the compensation as it is a very very small contribution. So I would like to decline the compensation this time.
However, this will inspire me and make me contribute more. 
I also want to thank you, appium project has indeed facilitated the automation

**Comment by jlipps** [comment]
thanks @Jiyvn, we very much look forward to your future contributions as well!

**Pull request merged**
