### PR TITLE
capabilities - applicationName

### PR DESCRIPTION
**Pull request by red-avtovo**
Provided serial number of device as `applicationName` of the node instance.
That will help if you need to execute operation on specific device on a node, which connected to selenium grid.
To do that just add this into `desired capabilities`:
```
capabilities.setCapability("applicationName", idenifier);
```

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@red-avtovo Do we have `applicationName` as caps? https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#appium-server-capabilities

**Comment by red-avtovo** [comment]
No, we don't.
It's one of not-documented parameter, that my friend found.
Unfortunately, `udid` and `deviceName` are not working properly, but `applicationName` does

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach ping

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget This capability is an undocumented one and can be used by Grid to select nodes. We don't use for any purposes in Appium explicitly. See
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3660
https://groups.google.com/forum/#!topic/selenium-users/PRsEBcbpNlM
for more details.

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach cool. @red-avtovo Can you make travis happy?

**Comment by SrinivasanTarget** [comment]
@red-avtovo Can you make travis happy?

**Comment by SrinivasanTarget** [comment]
@red-avtovo Can you complete this or i'm happy to fix this from here.

**Comment by red-avtovo** [comment]
Will do that soon. Sorry, was on vacation

**Comment by SrinivasanTarget** [comment]
> Will do that soon. Sorry, was on vacation

Np

**Comment by red-avtovo** [comment]
@SrinivasanTarget Yay! Let's merge

**Pull request merged**
