### PR TITLE
Refractor and Doc Updates

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
Expose VNC port and Doc Updates

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@saikrishna321 ping

**Comment by SrinivasanTarget** [comment]
@saikrishna321 May be it makes sense to create two new docker files like how selenium manages here with opt out feature as vnc.

**Comment by saikrishna321** [comment]
@SrinivasanTarget one with VNC as debug and other without ?

**Comment by SrinivasanTarget** [comment]
Yes like [this](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChromeDebug/Dockerfile)

**Pull request merged**
