### PR TITLE
Custom node config

### PR DESCRIPTION
**Pull request by PatrickDuncan**

### CODE REVIEW

**Comment by butomo1989** [comment]
Hi @PatrickDuncan , 

Thank you for your PR. we really appreciate it. I think it would be better to pass each variable through docker-parameter instead of using your own custom json. This process can be done through [those lines](https://github.com/appium/appium-docker-android/blob/master/Appium/generate_config.sh#L5-L31). What do you think?

**Comment by PatrickDuncan** [comment]
Hi @butomo1989 ,

You're welcome, thank you for your hard work. We're aware of the env variables that get interpolated into the node config and they work perfectly. However, based on our architecture we need the ability to pass our own node config file into the container.

**Comment by butomo1989** [comment]
Hi @PatrickDuncan , 

Thank you for the reply. The idea of using your own json file is great but to be honest, I prefer to pass all needed environment variables to container instead of using custom json because it is more transparent and it might benefit other people who want to have similar configuration that you have. May I know what kind of additional variables in your custom json that we do not support in generate_config.sh?

**Comment by PatrickDuncan** [comment]
I agree, we're not actually adding any new elements to the configuration! In our architecture we generate the node config before turning up the container so we need the ability to override the default behaviour of generating a config.

I think that it's great to have different options instead of locking user's into a certain flow.

**Comment by PatrickDuncan** [comment]
This is dependent on PR #75 , but #75 is useful on its own in my opinion.

Yes we're doing something along those lines, but we do have cleanup mechanisms for the files.

Passing the environment variables will not work in our use case because we create the config files beforehand. I completely understand where you're coming from, but the architecture/use case my coworkers have decided on needs this feature.

**Comment by PatrickDuncan** [comment]
Hey @butomo1989 ,

I can now say that we're using [AppiumConnect](https://github.com/Orasi/AppiumConnect) for device discovery and this image for Appium server turn up. AppiumConnect generates a nodeconfig file so this PR is a compatibility bridge between the two.

We're using AppiumConnect predominantly for its universal compatibility with Android, iOS, Mac, Linux and Windows.

**Comment by butomo1989** [comment]
Hi @PatrickDuncan , 

Sorry for late reply. Sure, For me it is fine if user want to use their own custom json file. It might have special cases that is required to use your custom one. I will approve this PR and merge to master. :)

**Pull request merged**
