### PR TITLE
Update to seperate emu & device images

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
**Changes:**

Single DockerFile is separated to two docker files,
1)Docker Image to work only with real device
2)Docker Image to work with emulator's

- Removed all the Android API's except Android API 24
- Appium Server is updated to point to beta without being locked to shrinkwraped dependencies latest driver versions released.
- Reduced few layers.
- Emu support without using docker-machine's
- Real device support through docker-machine's

@saikrishna321 Can you please review this?

**Next Step:**  

- we need to update the ReadMe and link to appropriate docker hub registries here: https://hub.docker.com/u/appium/dashboard/
- Update Travis Config's
- Publish a beta/release version

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@saikrishna321 FYI Real device test logs: https://gist.github.com/SrinivasanTarget/9e396aadc1b150ba653ca4c40c8c2c3e

**Comment by saikrishna321** [comment]
@SrinivasanTarget i'm still unable to run it inside the docker-machine. Will look into it again

**Comment by SrinivasanTarget** [comment]
Sure

**Comment by saikrishna321** [comment]
@SrinivasanTarget works fine on docker-machine. Will merge this and create a different card to fix the travis

**Pull request merged**
