### PR TITLE
fix #14 emulator boot

### LINKED ISSUE #14: boot android emulator on container up
Currently booting the container does not bring up  android emulator 

```
[saikrisv@insaikrisv-2 Desktop ]$ docker exec -it d4ba0f64b861 bash
root@d4ba0f64b861:/opt/node# appium -v
1.6.3
root@d4ba0f64b861:/opt/node# adb devices
List of devices attached
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

root@d4ba0f64b861:/opt/node# adb devices
List of devices attached

root@d4ba0f64b861:/opt/node#
```

### PR DESCRIPTION
**Pull request by saikrishna321**

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@saikrishna321 Can you change the author and amend the commit again?

**Comment by SrinivasanTarget** [comment]
```--abi armeabi-v7a ``` instead of ```x86``` in emulator creation

**Comment by irfanah** [comment]
this fix will still not show the connected devices

**Comment by SrinivasanTarget** [comment]
Yup Do you have any solutions in mind?

**Pull request closed without merging**
