### PR TITLE
Connection by air

### PR DESCRIPTION
**Pull request by red-avtovo**
Added ability to connect to android devices by air

### CODE REVIEW

**Comment by butomo1989** [comment]
Hi @red-avtovo , 

Thank you for the PR. As far as I remember if the device connected with adb (though cable or air), it will recognise directly with the old implementation / you do not need to pass device name through parameter again. or do I miss something?

**Comment by red-avtovo** [comment]
If device is connected to some random charger and `tcpip` mode is activated for `adb` daemon, then you need to connect to device by executing the command:
`adb connect <ip address of device>:<adb port>`

**Comment by red-avtovo** [comment]
The process described here: https://developer.android.com/studio/command-line/adb.html#wireless

**Comment by SrinivasanTarget** [comment]
@red-avtovo Thanks for your PR... This doesn't work if the device doesn't listen for TCP conn. Can you please specify that also in ReadMe with android dev help link.

**Comment by red-avtovo** [comment]
Now it's ready and passes all the tests. I even checked that on my testing environment.
Say if I'm still missing something in this PR

**Comment by butomo1989** [comment]
It looks good to me, but I still have 2 more questions:
1. Based on the docs we need to connect devices via cable (step 1 - 5)? could we skip those steps / could we directly jump to step 6? if not where do you run adb tcpip 5555? on host or docker container?
2. Are we always using port 5555? if yes, could we maybe hard coded it and pass only the IP address of device(s) to docker container?

Sorry for those late questions @red-avtovo

**Comment by red-avtovo** [comment]
1. We can jump to 6th step if our device already switched to `tcpip` mode and available in network.
2. You can specify whatever port you want, as soon as it's available on your device. Then you will need to provide proper addresses to docker container by passing `-e ANDROID_DEVICES=192.168.1.3:1234,192.168.1.3:4321`. After that, adb will connect to all of them and generate the config file properly

**Comment by SrinivasanTarget** [comment]
Thanks @red-avtovo

**Pull request merged**
